### PR TITLE
Fix indentation of hanging "} ->".

### LINKED ISSUE #65: incorrect indentation when using ->
I think this is a bug with puppet-mode.

When using `->` to chain resources the indentation is wrong.

So basically typing this as is you will notice will result in the below:

``` puppet
file { '/tmp/testdir':
  ensure => directory,
  } ->
  file { '/tmp/testdir/somefile1':
    ensure => file,
    } ->
    file { '/tmp/testdir/somefile2':
      ensure => file,
      } ->
      file { '/tmp/testdir/somefile3':
        ensure => file,
      }
```

Expected result

``` puppet
file { '/tmp/testdir':
  ensure => directory,
}
file { '/tmp/testdir/somefile1':
  ensure => file,
}
file { '/tmp/testdir/somefile2':
  ensure => file,
}
file { '/tmp/testdir/somefile3':
  ensure => file,
}
```

### PR DESCRIPTION
**Pull request by Fuco1**
This PR fixes #65.

### CODE REVIEW

**Comment by Fuco1** [comment]
Bump

**Comment by bbatsov** [comment]
@Fuco1 You'll have to rebase this on top of the current `master`.

**Comment by Fuco1** [comment]
@bbatsov done, thanks!

**Comment by nmaludy** [comment]
Any idea when this will be merged and included in a release?

**Comment by Fuco1** [comment]
@nmaludy probably @bbatsov just forgot, from my side the patch is ready.

**Comment by bbatsov** [comment]
Indeed.

**Pull request merged**
