### PR TITLE
Add documentation on how to run ERT tests

### PR DESCRIPTION
**Pull request by runejuhl**

### CODE REVIEW

**Comment by lunaryorn** [comment]
@runejuhl Thank you very much, but we have `make test` for this purpose (which runs `ert-runner` under the hood).

**Comment by runejuhl** [comment]
Sorry about that, I've managed to completely overlook the Makefile. The README doesn't mention tests though, and they require `cask` to be run with `make test`... Would you prefer to scrap my changes, or do you want me to add a paragraph on `cask` instead?

**Comment by lunaryorn** [comment]
I think it's sufficient to document cask and 

```
$ cask install
$ make test
```

to run the tests.  I would not elaborate too much on Cask, though.  It's a fairly standard tool in Emacs Lisp nowadays, most people should already be familiar with it.

**Comment by juniorsysadmin** [comment]
Closed due to inaction

**Pull request closed without merging**
